[project]
name = "cipherbox"
version = "0.2.1"
authors = [{ name = "Bima Rizki" }]
description = "CRYPTX Encryption Tool by Bima"
readme = "README.md"
requires-python = ">=3.10"

dependencies = ["pycryptodome"]

[project.scripts]
cryptx = "cipherbox.cli:main"

